### ISSUE TITLE
Logging in to download takes user away from their search 

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#328] opened 2017-08-14 12:03 UTC
NBN Forum post from Mark Pollitt:
I'm logged into the Atlas. I go to explore a location, select a place and a radius, and a species list appears. All fine so far.
So I want to download the species list. I click download and it tells me I need to login to download records - hmmm. I hit the login button and it takes me to the records page for all 215 million atlas records.
Not very useful...

Can it be set up to remember your search after logging in and take you to that same page?

**Comment by MandyHenshall** [comment] 2017-08-15 08:28
I didn't read this properly and Mark was already logged in and it then asked him to login to download.  I've just tried and it did the same for me from searching as described above.
![login to download](https://user-images.githubusercontent.com/27201815/29308001-faa1b2e6-819b-11e7-8351-877724e768c8.jpg)

**Comment by djtfmartin** [comment] 2017-08-15 09:16
closing. duplicate of #311

**Closed as completed by djtfmartin** 2017-08-15 09:16 UTC
Labels: bug
