### ISSUE TITLE
Output grid refs at lower resolution than when uploaded

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#355] opened 2017-09-07 15:21 UTC
Email through regarding BBS data downloads: It seems that the Atlas downloads limits Grid Refernce accuracy to six figures (e.g. SJ296143) even when more accurate GRs are part of the original record.

**Comment by djtfmartin** [comment] 2017-09-07 15:35
Cant reproduce.

Heres what i did.

1) https://records.nbnatlas.org/occurrences/search?q=grid_ref:SJ296143
2) Downloaded the 6 records
3) I can see the full res grid reference in the OGSR column

<img width="1153" alt="screenshot 2017-09-07 16 34 16" src="https://user-images.githubusercontent.com/444897/30171649-780f71c2-93ea-11e7-95a5-517be02fd680.png">

**Comment by EllaVogel** [comment] 2017-09-07 15:50
Reopening, because I think the point he was making is that the records were supplied with a more accurate grid reference than the 6 figures given in column Z. I think these may have been supplied as 8 figure grid refs

**Comment by EllaVogel** [comment] 2017-09-07 16:08
Actually, lets put this one on hold for a moment. Waiting for extra confirmation that the records were supplied at a higher precision.

I'll update when I can.

**Comment by EllaVogel** [comment] 2017-09-11 08:13
The original issue is correct. An example sent through: A BBS record of Schistidium pruinosum from Breidden Hill was returned by a polygon search on the NBN but summarised to SJ288139. The original BBS record gives the accurate GR (SJ28841398)

**Comment by djtfmartin** [comment] 2017-09-11 08:47
thanks @EllaVogel 
Have you got a link to an example record in the Atlas ?

**Comment by djtfmartin** [comment] 2017-09-11 08:54
Ive just checked the raw BBS data and we don't have any records supplied with the grid reference SJ28841398.
The only reference to SJ28841398 is in a comments field. Screenshots from the raw data

<img width="1268" alt="screenshot 2017-09-11 09 52 47" src="https://user-images.githubusercontent.com/444897/30266388-1c986c96-96d7-11e7-9b96-2bb51ab01871.png">
<img width="1112" alt="screenshot 2017-09-11 09 53 08" src="https://user-images.githubusercontent.com/444897/30266386-1c8d5612-96d7-11e7-9863-a35662c1a9f6.png">

**Comment by EllaVogel** [comment] 2017-09-11 10:03
Thanks Dave, I'll pass this info onto the person who raised the issue. The truncation must have happened before the record got to us

**Comment by sophiathirza** [comment] 2017-09-11 10:12
#331 may be the same issue

**Comment by sophiathirza** [comment] 2017-09-19 09:28
The maximum resolution of records transferred to the NBN Atlas was 100m (6 fig grid references). The JNCC have confirmed that any datasets with a public resolution greater than 100m will have to be resubmitted to the NBN directly from the data provider.

**Comment by sophiathirza** [comment] 2017-09-21 08:17
I will close this now as the BRC are aware that they need to resend the data to us.

**Closed as completed by sophiathirza** 2017-09-21 08:17 UTC
Labels: records
