### ISSUE TITLE
Number of Species Lists available is confusing

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#370] opened 2017-09-15 14:48 UTC
Via the species search link (accessed via HELP > Lists you access about 133 species lists.  

If you use the 'Search NBN  Atlas datasets' drop down you can access 238 Species-lists.  This seems confusing but it looks like this 238 includes 105 lists that are 'Identified' - which means they are not currently available in the Atlas.  Some of the 105 are duplicated names (eg UKBMS species) or nonsense names (eg xzxzxzx) and don't link to a dataset BUT some (such as Scottish Biodiversity List) have been wrongly tagged as 'Identified' and should be 'Data available'.

Is it worth keeping the 'Identified' tag? What is it being used for?  And can the correct tag be assigned to the Scottish Biodiversity List so that it is found when searching 'Data available'?

**Comment by sophiathirza** [comment] 2017-09-15 15:00
duplicate: #366

**Comment by sophiathirza** [comment] 2017-09-15 15:01
It's a problem with the classification of the data, it's not a bug.

**Comment by sophiathirza** [comment] 2017-09-15 15:02
Also, there are test datasets, with strange names, that have been created in error that need to be deleted.

**Comment by sophiathirza** [comment] 2018-07-20 13:58
@reupost  can the correct tag be assigned to the Scottish Biodiversity List so that it is found when searching 'Data available',  please?

**Comment by reupost** [comment] 2018-07-23 12:09
Could you give me the URLs for these searches, please? It helps to quickly find the issue. For example, I can find the list here https://lists.nbnatlas.org/public/speciesLists which is the one from the Help pages 'Lists' section, so I'm not sure where the problem is.

**Comment by sophiathirza** [comment] 2018-07-23 13:58
@CEJohnston 'identified' datasets could be used as those datasets that have been identified as being useful to have on the NBN Atlas but that we don't have records for. I think that is the point of the classification.

**Comment by sophiathirza** [comment] 2018-07-23 13:58
Close as it's a duplicate of #366 and I have answered @reupost question there.

**Closed as completed by sophiathirza** 2018-07-23 13:58 UTC
Labels: #2, lists
