### ISSUE TITLE
Isle of Man focus is lost when viewing spatial portal 

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#466] opened 2018-01-22 12:06 UTC
Analyse Data from https://isleofman.nbnatlas.org/ (search > map > analyse data) takes you to https://spatial.nbnatlas.org/ and 'loses' Isle of Man specific map

**Comment by sophiathirza** [comment] 2018-01-23 13:15
duplicate of #468

**Closed as completed** 2018-01-23 13:15 UTC
Labels: bug, Isle of Man
