### ISSUE TITLE
Replace data resource verification status text with indication of number of accepted records

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#459] opened 2018-01-06 11:09 UTC
Replace the verification status text on the data resource page with an indicator of the proportion of accepted records.

If it's not possible for launch to show the proportion of accepted records, could the verification text be removed, as I think that it will be confusing to have verification at both the data resource and record levels.

**Comment by reupost** [comment] 2018-01-10 12:00
Duplicate of #460

**Closed as completed by reupost** 2018-01-10 12:00 UTC
