### ISSUE TITLE
Error 500: internal service error on registration

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#113] opened 2016-07-22 15:43 UTC
User received the following error (Error 500: internal service error) on attempting to register with the Atlas.  CJ Emailed screen shot to Dave 27th June 2016

**Comment by djtfmartin** [comment] 2017-03-23 13:59
@CEJohnston cant reproduce this.  Closing but please reopen if its reproduceable

**Closed as completed by djtfmartin** 2017-03-23 13:59 UTC
Labels: bug
