### ISSUE TITLE
EYA is displaying absence records

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#270] opened 2017-06-12 14:37 UTC
may be related to #260 and #252 (email received 12/6/17 at 15.20 AW)
If you log in, and go ‘Locations’ > ‘Explore by address, postcode or location’ > type in “Scilly” you get a map of records around the Isles of Scilly. Filter those for ‘molluscs’ and again for ‘Crassostrea gigas’ (Pacific oyster) and the table says there are 35 records, all of which are shown on the dynamic map as a collection of points within the search radius. 

But if you then click on “list of records” link under the species name in the table to the left of the map, this takes you to the ‘Occurrence records’ page and interactive map, and suddenly all but one of the points has disappeared. The headline still says “35 results for…”, and all 35 are listed in the ‘Records’ tab, but there’s only one point. Click on the point on the map and you get not one record, nor 35, but 5! So the map and list don’t tally. Click on the map link to see the 5 records and the list of 35 becomes a list of 5!

If you change the ‘Colour by’ dropdown from Variable grids to one of the points options, this does narrow the results down to the one record with ‘Occurrence status’ = “present” but there is no explanation on any of the pages about what has happened in presenting the data, nor why, which is confusing.

I think some kind of simple text is needed to explain, eg -
‘Occurrence records shown in the interactive map have been filtered to exclude those where ‘occurrence status’ = “absent” ‘
Or something like that? 

Or would it be better to offer this as a ‘Colour by’ dropdown option somehow, to display “absent” records with a different symbol entirely? (But this shouldn’t be optional - absence records need to be clearly shown as such wherever they occur…)

I don’t fully understand the system behaviour here, but perhaps you could give this issue a bit more thought? I suppose differentiating ‘presence’ from ‘known absence’ data is a bit of a minefield - definitions need to be clear (ie ‘we’ve established its not there’ vs ‘we just didn’t find it in this survey’ etc), and its really fundamental that data which says “something is NOT HERE” cannot be easily mistaken for the exact opposite! I think historically, adding ‘absence’ data came quite late to the Gateway (you’ll know better than me!), and maybe providing some guidance on its use within Atlas is also needed?

**Comment by djtfmartin** [comment] 2017-11-13 17:28
EYA filters absence data now.

this was a duplicate of #252

**Closed as completed by djtfmartin** 2017-11-13 17:28 UTC
Labels: bug, #2
