### ISSUE TITLE
Reduce options of pre-loaded boundaries to just display boundaries within Scotland

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#89] opened 2016-05-17 10:42 UTC
Reduce options of pre-loaded boundaries to just display boundaries within Scotland within 'Search a region to explore' 

http://regions.als.scot/#rt=National+parks

I think it is just National Parks which are displayed for the UK and not just Scotland

**Comment by djtfmartin** [comment] 2016-05-17 16:25
We need to source a layer for Scottish National Parks to do this.

**Comment by RachelStroud** [comment] 2016-09-08 09:05
@CEJohnston  are you able to source this layer from the National Parks Scotland for Dave.  It is not a high priority task but would be good to have lined up ready for the future

**Comment by djtfmartin** [comment] 2016-09-08 09:12
This is actually a duplicate of #104

@CEJohnston has source several layers, but we actually need a single combined layer if we want a categories of "National Parks for Scotland".

**Comment by RachelStroud** [comment] 2016-09-08 09:15
@CEJohnston I suggest we approach RSPB and ask them if the GIS team can make a single layer for us

**Comment by CEJohnston** [comment] 2016-09-08 09:28
There is no single Scottish layer showing National Parks prepared by anyone.  The Scottish Government  supplies the boundaries separately for the two National Parks.  I could look at creating a single combined layer from the two that have been sourced as I have QGIS here - if I get stuck I can ask the RSPB guys for help next week.  We would just need to remember to update the combined layer when boundaries change.

**Comment by CEJohnston** [comment] 2016-09-09 09:58
Have just uploaded to S3 a combined national park file for Scotland - hope it works. There are only two parks in Scotland.

**Comment by RachelStroud** [comment] 2016-09-21 10:58
@djtfmartin please can you remove the national parks layer which appears to be sitting behind the new Scotland NP layer (you can see NPs outside Scotland but they don't occur on the left hand menu). 

We appreciate that this will also remove the Forest Park boundary which is fine.  @CEJohnston will source you a new Forest Park layer to add as a separate category

**Comment by djtfmartin** [comment] 2017-03-23 11:10
Done

**Closed as completed by djtfmartin** 2017-03-23 11:10 UTC
