### ISSUE TITLE
Tools > Point to Grid.  Box is too large for the content - affect visibility of buttons

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#50] opened 2016-04-26 14:17 UTC
...  the 'Cancel', 'Back' and 'Next' buttons are obscured and have to scroll to see them

**Comment by djtfmartin** [comment] 2016-05-03 12:47
I cant reproduce this one. Closing. Please re-open if you can reproduce and detail the browser in use.

**Closed as completed by djtfmartin** 2016-05-03 12:47 UTC
Labels: bug
