### ISSUE TITLE
No results or intermittent results for Laetiporus sulphureus

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#238] opened 2017-04-19 08:21 UTC
Email to Support from 11.04.17 "Why would there not be any of the above species listed on the NBN Atlas?"

Help has been given and some results returned through spatial portal, but now nothing is coming up again, through spatial portal or species search.

**Comment by djtfmartin** [comment] 2017-04-19 08:38
I assume the system was down for a period. Cant reproduce.

**Comment by MandyHenshall** [comment] 2017-04-19 12:26
I'm still getting the same for the top 4 or 5 species on this page: https://species.nbnatlas.org/search?fq=idxtype%3ATAXON&q=Laetiporus+sulphureus. See map at https://species.nbnatlas.org/species/BMSSYS0000046904
![chicken in wood 0 records](https://cloud.githubusercontent.com/assets/27201815/25179911/c7b8fbcc-2503-11e7-944b-f1a2ac2acf58.jpg)

**Comment by djtfmartin** [comment] 2017-04-19 12:56
Thanks for reopening. I see the problem now.

I think this will be fixed after the UKSI update is applied

**Comment by MandyHenshall** [comment] 2017-04-19 12:57
Okay, thanks Dave.  Do we know when that is likely to be?

**Comment by djtfmartin** [comment] 2017-04-19 13:00
Not yet. Still working through issues with UKSI

**Comment by djtfmartin** [comment] 2017-04-25 11:07
this is fixed.

**Closed as completed by djtfmartin** 2017-04-25 11:07 UTC
Labels: bug
