### ISSUE TITLE
Know age of the harvest rates 

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#546] opened 2018-07-18 15:13 UTC
Dataset metadata requirements.

**Comment by CEJohnston** [comment] 2018-07-23 08:28
Comment from the Welsh stakeholder group: Show data profile (how old is data) in metadata for each dataset.

**Comment by c-van-dierkson** [comment] 2020-03-30 08:58
Is this a duplicate of #396? @CEJohnston @sophiathirza

**Comment by sophiathirza** [comment] 2020-03-30 10:02
@c-van-dierkson yes.

**Closed as completed** 2020-03-30 13:49 UTC
Labels: records, Wales, requirements needed, Scotland
