### ISSUE TITLE
Adding a pre and post 1999 date range function on main search

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#334] opened 2017-08-17 09:04 UTC
To be able to easily map the post 2000 records;

Suggested by user to save having to go through the occurrence tab, customisable filters or via the form in the advanced search options.

**Comment by djtfmartin** [comment] 2017-08-17 09:07
duplicate of #255

**Closed as completed by djtfmartin** 2017-08-17 09:07 UTC
