### ISSUE TITLE
Problem with references

### ISSUE THREAD

**Issue by katieoli** [nbnuk/nbnatlas-issues#759] opened 2019-07-17 14:19 UTC
There's some kind of error in the references list. The following text appears underneath the image when looking up Epiphragma ocellare (or others).

Showing same error:

https://species.nbnatlas.org/species/NBNSYS0100003055

and

https://species.nbnatlas.org/species/NBNSYS0000007404

and

https://species.nbnatlas.org/species/NHMSYS0000376035#overview

and something similar with this one:

https://species.nbnatlas.org/species/NHMSYS0000376015#overview

This one is fine:

https://species.nbnatlas.org/species/NHMSYS0001387363

**Comment by sophiathirza** [comment] 2019-07-17 20:54
This is a duplicate of #652

**Closed as completed by sophiathirza** 2019-07-17 20:54 UTC
