### ISSUE TITLE
Consider a switch to OSGB36 from WGS84 for mapping displays.

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#167] opened 2016-09-16 15:43 UTC
Initial discussion with @djtfmartin 16/09/2016 - ideas to be developed further re pros and cons of such a switch.

**Comment by djtfmartin** [comment] 2017-03-24 12:08
Duplicate of 

https://github.com/nbnuk/als-issues/issues/117

**Closed as completed by djtfmartin** 2017-03-24 12:08 UTC
