### ISSUE TITLE
Download fails in Darwin Core

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#345] opened 2017-08-29 11:51 UTC
Is this a known issue or do we need more info on exactly what he was trying to download?

I tried to download data from the Atlas in Full Darwin Core format, and I received an email stating that the download had failed.  This also happened when I attempted to select custom fields in a spreadsheet download.  I can however download the basic spreadsheet format fine.  Is there a fix for this coming soon?

**Comment by djtfmartin** [comment] 2017-08-31 14:55
i think this was caused by the same issue affecting #344 so it should be fixed now

**Closed as completed by djtfmartin** 2017-08-31 14:55 UTC
