### ISSUE TITLE
Add hyperlinks to descriptions data partner pages

### ISSUE THREAD

**Issue by GiselleSterry** [nbnuk/nbnatlas-issues#194] opened 2017-03-30 14:55 UTC
would like ability to add hyper links to free text on data partner pages e.g. for further info.

**Comment by GiselleSterry** [comment] 2017-04-05 08:25
We also want to use hyperlinks to link to NBN members page on our website. Member benefit.

**Comment by GiselleSterry** [comment] 2017-11-13 13:01
hi @sophiathirza do you know if this is possible. Want to also add in link to data sharing certificates.

**Comment by sophiathirza** [comment] 2017-11-15 09:52
No, it's not possible to add nicely formattted hyperlinks to these free text boxes. It's only possible to simply copy in the link, which doesn't look good.

**Comment by GiselleSterry** [comment] 2017-11-15 09:57
Do you know if this function could be added with some programming work? Either to existing or a new box?

**Comment by sophiathirza** [comment] 2017-11-15 10:00
Yes, it just needs a different input control and perhaps rendering of the text on the page.

**Comment by sophiathirza** [comment] 2018-07-20 11:45
Duplicate of #103

**Closed as completed** 2018-07-20 11:45 UTC
