### ISSUE TITLE
Suspect records for Crucian Carp and Tench??

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#331] opened 2017-08-15 13:11 UTC
Someone has contacted us regarding possible suspect records for Crucian Carp and Tench - they say around 20% of the records from a range of data providers and dates seem to be in suspect locations i.e. not near water....could this be investigated? 

https://species.nbnatlas.org/species/NHMSYS0000544635 
https://species.nbnatlas.org/species/NHMSYS0000544773

**Comment by sophiathirza** [comment] 2017-09-01 10:05
@SarahHyslop  would you send me their contact details please?

**Comment by sophiathirza** [comment] 2017-09-11 08:16
Details from email:

In the NBN Atlas I first click Species then (on this occasion) in Search for Taxa enter Tinca, then click on Tinca Tinca (Linnaeus, 1758)-Tench which takes me to the Occurence Records Map (6,629 records).  Click view map - map showing mass of 10 km yellow squares (variable grids).  Then zoom in to choose a square eg. SH77 showing 1 record.  Click view record, Provider:- Cofnod (22.02.2001), note grid ref., return to Occurence Record, click map (screen fills with yellow with SH77 in the middle) Choose Default Colour from dropdown menu. Now there is a very basic map with a red location (occurence) dot and I check that the coordinates are the same as in the Occurence Record.  Because of lack of detail in map switch to satellite view.  I then can zoom in and make final check of coordinates and look for water location.  In this particular example there is no fresh water anywhere in the area but there is a possible lake two miles away.

Try these:-

SO46 (North of Hereford) 2 records (1966 &1972)with same coordinates and a location shown in the vicinity of the National Trust Croft Castle. Helpfully one of the records gives a location as 'Shobdon Pools'.  However Shobdon is a village a full 3 1/2 miles to the SW where there are five quite distinct lakes to choose from.  

SH19 - could that be the River Severn?
SN44 - is another example where one has to search for a location of fresh water.

In SS87 the poor tench is all at sea off South Wales.  Plenty of water but the wrong sort.  (And there are three records for this location from 2002 & 2004 but where is it?!)

Finally another seafaring tench can be found well north of Wallasey Golf Course (SJ29) and on the same map two other fish seem to have got themselves well and truly lost in Moreton on the north end of the Wirral.

However probably the most frustrating records (and there are a great many of them) are where the  Occurence is shown on dry land but there are a number of distinct location possibilities within equal distance of the spot shown.  With a system using very precise grid references it is hard to see how a location on dry land could have ever recorded the presence of a freshwater fish!

**Comment by EllaVogel** [comment] 2017-09-11 10:20
Yes, there could be a link here. If the records were transferred from the gateway, they might have reduced precision. We could ask for a re-load to see if that fixes these errors with more accurate locations

**Comment by sophiathirza** [comment] 2017-09-18 11:11
I think the problem here is actually the low precision of the Tench data. Over 2000 records were supplied on the 10 km grid. The majority of the data has a six digit grid reference, so they may have the same problem.

**Comment by sophiathirza** [comment] 2017-09-19 09:45
I will close this as the problem is the low resolution of the data and we have identified that the maximum resolution of data transferred from the Gateway was 100 m.

**Closed as completed by sophiathirza** 2017-09-19 09:45 UTC
Labels: records
