### ISSUE TITLE
Number of records displayed is incorrect

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#339] opened 2017-08-22 10:21 UTC
There appears to be a bug affecting the number of records displayed against a resource.
 
Example: https://registry.nbnatlas.org/public/show/dr1485 says, generally, 56,863 records.
 
However, if I login and go through the download process, (View records> Download > Occurrence data in simple CSV format) then return to search results, the results now list 42,664 results, and, if I navigate back to https://registry.nbnatlas.org/public/show/dr1485 that page now also says 42,664. The number resets to 56,863 if I close the browser tab and reopen it.
 
Also, the download has 48,827 records, and the usage stats don't update.

**Comment by djtfmartin** [comment] 2017-08-22 12:13
usage stats are working now. this was a problem related with the als.scot domain (which has expired).

investigating the counts issue - but its not related to logins. I see the same issue logged in and logged out.

**Comment by djtfmartin** [comment] 2017-09-05 11:27
i think this was caused by a problem with one of the index servers that has now been fixed. Closing. Please reopen if you still see the issue

**Closed as completed by djtfmartin** 2017-09-05 11:27 UTC
Labels: bug
