### ISSUE TITLE
Additional info to be added to record summary

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#246] opened 2017-04-21 14:47 UTC
We have had a request for more information to be given in the record summary.  It is time consuming to have to open the record to see the main details and to switch back and forth from map.  Suggested we add: location name (locality), abundance, recorder (collector) and determiner (identified by).

![image](https://cloud.githubusercontent.com/assets/18594564/25282760/5c395b1a-26a9-11e7-9ede-e0782cdc87c8.png)

Might be good to add the same info to the pop-up box on the map that you get when you mouse over a point:
![image](https://cloud.githubusercontent.com/assets/18594564/25282860/a9a6c54a-26a9-11e7-8c88-a8e73e533c8d.png)

**Comment by c-van-dierkson** [comment] 2020-03-30 07:33
Duplicate of 430

**Closed as completed by c-van-dierkson** 2020-03-30 07:33 UTC
Labels: records, requirements needed
